name: Full CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1ï¸âƒ£ Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 3ï¸âƒ£ Sonar Scan
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -DskipTests \
            -Dsonar.projectKey=myproject \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 4ï¸âƒ£ Build JAR
      - name: Build JAR
        run: mvn clean package -DskipTests=true

      # 5ï¸âƒ£ Copy JAR to EC2
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/datastore-0.0.7.jar"
          target: "/home/ec2-user/app/datastore-0.0.7.jar"

      # 6ï¸âƒ£ Stop old JAR
      - name: Stop Old Application
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            PID=$(pgrep -f datastore-0.0.7.jar || true)
            if [ -n "$PID" ]; then
              echo "Stopping existing application with PID: $PID"
              sudo kill -9 $PID || true
            else
              echo "No old application running"
            fi

      # 7ï¸âƒ£ Start New JAR
      - name: Run New Application on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /var/log/app
            sudo chmod 777 /var/log/app

            cd /home/ec2-user/app

            nohup java -jar datastore-0.0.7.jar \
              --spring.datasource.url="jdbc:mysql://database-1.cwv0y4skwfjn.us-east-1.rds.amazonaws.com:3306/datastore?createDatabaseIfNotExist=true" \
              --spring.datasource.username="admin" \
              --spring.datasource.password="database-1" \
              --server.port=8084 \
              > /var/log/app/datastore.log 2>&1 &

            echo "ðŸš€ New Application Started Successfully"
